apiVersion: v1
kind: Service
metadata:
  name: rdza-service
spec:
  selector:
    app: rdza
  ports:
    - protocol: TCP
      port: 80        # Port on which the service will be exposed
      targetPort: 3030 # Port your app is listening on inside the pod
  type: LoadBalancer # This will expose the service externally (for cloud providers)